CREATE DATABASE IF NOT EXISTS beyondchats;
USE beyondchats;

CREATE TABLE IF NOT EXISTS articles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content LONGTEXT NOT NULL,
    url VARCHAR(255) NULL,
    published_at TIMESTAMP NULL,
    is_updated BOOLEAN DEFAULT FALSE,
    references JSON NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);